#!/bin/ash
if [ "$1" != "--noop" ]; then
    FILENAME=${DB_NAME}-`date +%Y-%m-%d`.sql.gz
    mysqldump -h ${DB_HOST} --user="${DB_USER}" --password="${DB_PASSWORD}" ${DB_NAME} --quick --lock-tables --add-drop-table | gzip > /tmp/${FILENAME}
    s3cmd put /tmp/${FILENAME} "s3://${S3_PATH}"
    rm /tmp/${FILENAME}
fi