#!/bin/ash
export SQL_ALLOW_EMPTY_PASSWORD=yes
echo -e "[mysql]\nuser=$DB_USER\npassword=$DB_PASSWORD" > .my.cnf
chmod 600 .my.cnf

if mysqladmin ping -h ${DB_HOST} -u ${DB_USER}; then
  echo "The database connection is alive."
  cat .my.cnf
else
  echo "Failed to establish the connection."
fi
